server:
  servlet:
    context-path: /snackmachine
  netty:
    h2c-max-content-length:

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  h2:
    console:
      enabled: true

name: Snackmachine Test
