server:
  servlet:
    context-path: /snackmachine

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:15006/snackmachine
    username: snackmachine
    password: snackmachine
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

